print(5 * 5) 
print("hello world")
user_feedback = ("how are you?")
print(user_feedback)
print("fine and yourself?")
print("Hello Python World!")
message = ("What's new gang?")
print(message)
message = ("Not much, how about you?")
print(message)
a, b, c = (1, 2, 3)
print(a,b,c)
user_feedback = ("how old are you?")
print(user_feedback)
user_age = 28
print(user_age)
message = ("I am 28 years old")
print(message)